name: Master Sync Logic
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      spec_path:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # We only need to checkout the Service Repo (Source)
      # The Redocly action handles the Destination repo internally
      - name: Checkout Service Repo
        uses: actions/checkout@v4

      - name: Repo File Sync
        uses: Redocly/repo-file-sync-action@v1
        with:
          # Source file from the service repo
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          SYNC_CONFIG: |
            - source: api/openapi.yaml
              dest: api-reference/${{ inputs.spec_path }}/spec.yaml
              repository: abcdeafasdfasdf/doc
              branch: main
          COMMIT_EACH_FILE: false
          # You can customize the message, but Redocly has a default one
          COMMIT_PREFIX: "Sync: ${{ inputs.service_name }} | "
          SKIP_PR: true # Set to true to push directly to the main branch
